
import 'package:flutter/material.dart';

import '../models/task.dart';

class TaskProvider with ChangeNotifier{
  List<Task> _taskItems = [
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'Autogenerated',
      requestedBy: '',
      requestedOn: '19/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: '',
      requestedBy: '',
      requestedOn: '19/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/13',
      requestedBy: '',
      requestedOn: '19/09/2022',
    ), Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/12',
      requestedBy: '',
      requestedOn: '19/09/2022',
    ), Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/11',
      requestedBy: '',
      requestedOn: '19/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/10',
      requestedBy: '',
      requestedOn: '19/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/10',
      requestedBy: '',
      requestedOn: '17/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/8',
      requestedBy: '',
      requestedOn: '17/09/2022',
    ),Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/7',
      requestedBy: '',
      requestedOn: '17/09/2022',
    ),Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/6',
      requestedBy: '',
      requestedOn: '16/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/4',
      requestedBy: '',
      requestedOn: '15/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/3',
      requestedBy: '',
      requestedOn: '15/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/2',
      requestedBy: '',
      requestedOn: '15/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'GTU/PUR/INQ/2022/1',
      requestedBy: '',
      requestedOn: '14/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'RF/1/14-09-2022',
      requestedBy: '',
      requestedOn: '14/09/2022',
    ),
    Task(
      module: 'Student Activity',
      university: '',
      additionalDetails: '	Country :- / Semester I',
      requestedBy: '210060107002 - rakesh malhotra',
      requestedOn: '03/09/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'RFQ/2/26-08-2022',
      requestedBy: '',
      requestedOn: '26/08/2022',
    ),
    Task(
      module: 'RFQGeneration',
      university: '',
      additionalDetails: 'RF/1/26-08-2022',
      requestedBy: '',
      requestedOn: '26/08/2022',
    ),
    Task(
      module: 'Demand Note',
      university: '',
      additionalDetails: 'AA/2PR/62/28-06-2022 / Category: Purchase--Consumables / Indent Value: 650.00 / Actual Indentor: Tarun Meht',
      requestedBy: '',
      requestedOn: '28/06/2022',
    ),
    Task(
      module: 'Demand Note',
      university: '',
      additionalDetails: 'AA/AAPR/57/27-06-2022 / Category: Purchase--Office Equipment / Indent Value: 4000.00 / Actual Indentor: Vinod GTU',
      requestedBy: '',
      requestedOn: '09/06/2022'
    ),
    Task(
        module: 'Demand Note',
        university: '',
        additionalDetails: 'AA/AAPR/19/08-06-2022 / Category: Purchase--Office Equipment / Indent Value: 1000.00 / Actual Indentor: Vinod GTU',
        requestedBy: '',
        requestedOn: '08/06/2022'
    ),
    Task(
        module: 'Demand Note',
        university: 'College - GPERI',
        additionalDetails: '	12/12PR/63/03-09-2021 / Category: Purchase--Consumables / Indent Value: 52500.00 / Actual Indentor: Anil Patil',
        requestedBy: 'Modi Hitesh',
        requestedOn: '25/05/2022'
    ),
  ];

  List<Task> get taskItems{
    return [..._taskItems];
  }

}